support bool field
zilliztech/milvus-insight pull request #258
Opened 2021-11-18 07:48 UTC by nameczz

Signed-off-by: nameczz <zizhao.chen@zilliz.com>

2021-11-18 09:34 UTC, shanghaikid requested changes

2021-11-18 09:34 UTC, shanghaikid commented on client/src/utils/search.ts
> +      : f._fieldType === 'Bool'
enum

2021-11-19 02:24 UTC, Tumao727 approved these changes

2021-11-19 03:13 UTC, shanghaikid approved these changes

2021-11-19 03:25 UTC, merged